services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $logDir: "%kernel.logs_dir%"
      $pageClass: "%pw.entity_page%"

  Pushword\Version\:
    resource: "../*"
    exclude: "../{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Installer/install.php}"


  Pushword\Version\VersionController:
    tags: ["controller.service_arguments"]
    autowire: true
    autoconfigure: true
